#!/usr/bin/env bash

# WEATHER_API_KEY="af5359375f0ccacb50dba29c03c4c7a4" # Darksky deprecated
API_KEY="2b8ef531db84aff20910dedcede815e9"
# location="-27.1585,-51.1585"
lat="-27.1585"
lon="-51.1585"
units=ca
# url="https://api.darksky.net/forecast/${WEATHER_API_KEY}/${location}?units=${units}&exclude=minutely,hourly,daily,alerts,flags"

url="https://api.openweathermap.org/data/2.5/onecall?lat=${lat}&lon=${lon}&appid=${API_KEY}"

api_response=$(curl -s "${url}")

echo ${api_response}

temperature=$(echo "${api_response}" | jq '.current.temp' | xargs printf '%.*f\n' 0)
weather_icon=$(echo "${api_response}" | jq '.current.weather.icon')
summary=$(echo "${api_response}" | jq '.current.weather.description' | tr -d '"')

echo ${temperature}

case "${weather_icon}" in
  '"clear-day"')
    icon=" "
    ;;
  '"clear-night"')
    icon=" "
    ;;
  '"rain"')
    icon=" "
    ;;
  '"snow"')
    icon=" "
    ;;
  '"sleet"')
    icon=" "
    ;;
  '"wind"')
    icon=" "
    ;;
  '"fog"')
    icon=" "
    ;;
  '"cloudy"')
    icon=" "
    ;;
  '"partly-cloudy-day"')
    icon=" "
    ;;
  '"partly-cloudy-night"')
    icon=" "
    ;;
esac

echo -n "%{T1}%{F#01AB84}${icon}%{F-}%{T-}  ${summary}  %{F#01AB84}%{F-} ${temperature} °C"
